services:
  # Backend service with hot reload using volumes
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - STATIC_DIR=../frontend/dist
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./frontend/dist:/frontend/dist
      - go-modules:/go/pkg/mod
    working_dir: /app
    command: go run cmd/server/main.go
    restart: unless-stopped
    networks:
      - rambo-network
    depends_on:
      - frontend

  # Frontend service with webpack dev server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    networks:
      - rambo-network

volumes:
  go-modules:

networks:
  rambo-network:
    driver: bridge
