version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
    volumes:
      - ./frontend/dist:/root/frontend/dist
    restart: unless-stopped
    networks:
      - rambo-network

networks:
  rambo-network:
    driver: bridge
